### ISSUE TITLE
Parallel execution mode of the CPU OptimizationSolver

### ISSUE THREAD

**Issue by GaboFGuerra** [lava-nc/lava-optimization#170]
### User Story
As a user of the OptimizationSolver I want to run the CPU Optimization solver with many parallel configurations running simultaneously to get higher solution probability and a lower time to solution.

### Conditions of satisfaction

- User can explicitly invoke the number of parallel copies of the solver network in SolverConfig. 
- At runtime, the network state is read from the network with the best cost.
- The user can give the solver a set of hyperparameters in SolverConfig which parameterize each copy of the network solver.

### Acceptance Tests
With CPU backend:
- Number of parallel copies of the network in SolverConfig results in an equivalent number of SNN + CostIntegrator copies on the SolverProcess and SolverModel.
- ReadGate's RefPorts for solution readout and spike counters for cost reading are equal the number of copies of the network.
- Solver network and solution readout processes are correctly connected.
- The input set of hyperparameters are correctly propagated and distributed into the solver network copies.
- At runtime, the network state is read from the network with the best cost.

### Tasks
- [x] [GG, 4ih] Decouple solver process hierarchy into component to be replicated (solver network: VariablesImplementation, CostMinimizer, CostIntegrator) and component to be modified (solution reader: SolutionReadout, ReadGate).
- [x] [GG, 3ih] Modify SolverConfig to accept an iterable of hyperparameters, one per solver replica.
- [x] [GG, 2ih] Propagate hyperparameters iterable up to the process builder.
- [x] [GG, 4ih] Clone SolverNetwork for each hyperparameter set, follow prototype design pattern if beneficial.
- [x] [GG, 3ih] Create a SolverNetwork copy per hyperameter set.
- [x] [GG, 4ih] Modify ReadGate for multiple input cost values and for choosing the index of the best cost, require updating of port shape.
- [x] [3ih] Modify the solution reader processes to replicate the ref ports for solution readout.

**Lava version:**
- [x] **0.3.0** (feature release)

**I'm submitting a ...** 

- [x] feature request

**Other information:**

```
insert the output from lava debug here
```
