### ISSUE TITLE
CPU OptimizationSolver with annealing schedule for solving QUBO problems 

### ISSUE THREAD

**Issue by GaboFGuerra** [lava-nc/lava-optimization#173]
### User Story
As a user of the OptimizationSolver with CPU backend, I want to chose an annealing schedule  to control the exploration-explotation trade-off  of the search algorithms across runtime.

### Conditions of Satisfaction
- User can specify temperature schedule from solver's API.
- The annealing schedule affects the temperature parameter value on the NEBM neuron model during runtime at the timesteps specified by the time series.
- The annealing schedule affects the noise amplitude for the SCIF neuron model during runtime at the timesteps specified by the time series.
- The temperature schedule works for both Loihi 2 and CPU backends

### Acceptance Tests
- Solver offers an API to receive input timeseries as annealing schedule.
-  Temperature value of the NEBM neuron model follows the annealing schedule through time.
-  Noise amplitude of the SCIF neuron model follows the annealing schedule through time.

###Tasks
- [x] [PS, 8ih] Device Loihi-compatible annealing schedule
- [x] [PS, 3ih] Write unit test based on DWave's annealing (NEAL).
- [x] [PS, 4ih] Add new variable across processes to take annealing schedule.
- [x] [PS, 3ih] Update neuron model to update temperature at given timesteps. 

**Lava version:**
- [x] **0.3.0** (feature release)

**I'm submitting a ...** 

- [x] feature request

**Other information:**

```
insert the output from lava debug here
```
