### ISSUE TITLE
Loihi 2 OptimizationSolver with annealing schedule for solving QUBO problems

### ISSUE THREAD

**Issue by GaboFGuerra** [lava-nc/lava-optimization#174]
### User Story
As a user of the OptimizationSolver with Loihi2 backend, I want to chose a linear or exponetial annealing schedule (user only provides decay parameter not time series) to control the exploration-explotation trade-off  of the search algorithms across runtime.

### Conditions of Satisfaction
With Loihi 2 backend:
- User can pass a time series to the solver which defines the temperature schedule.
- The annealing schedule affects the temperature parameter value on the NEBM neuron model during runtime at the timesteps specified by the time series.
- The temperature schedule works for Loihi 2 backend

### Acceptance Tests
With Loihi 2 backend:
- Solver offers an API to receive input timeseries as annealing schedule.
-  Temperature value of the NEBM neuron model follows the annealing schedule through time.

**Lava version:**
- [x] **0.3.0** (feature release)

**I'm submitting a ...** 

- [x] feature request

**Other information:**

```
insert the output from lava debug here
```
### Tasks:

- [x] Knowledge transfer PS->GG, AP, AM. [PS, AM, AP, GG, 2ih]
- [x] Validate the NEBM and Loihi2 backend works. [AP, GG, 6ih]
- [x] Write neuron model tests. [GG, AP, AM, 4ih]
- [x] Update NEBM ucode, NCProcModel and Process to support temperature decay [AP, AM, GG, 3id].
- [x] Write unit tests for solver [AP, AM, GG, 4ih]
- [x] Integrate the OptimizationSolver and OptimizationSolverProcess changes into a clean branch and test [AP, AM, GG,1id].
- [ ] Open PR, review and merge [AP, AM, GG, 1id].

7id/3P

**Comment by awintel** [comment]
I think this story needs a new owner. SR is on VRP.
